title: Rainy Dong
email: rainydong@stanford.edu
description: >-
  Postdoc at Stanford GSE studying early reading and literacy development.
theme: jekyll-theme-minimal
url: "https://rainy323.github.io" 
logo: /assets/profile.jpeg

include:
  - _pages
